del /Q backup.rar
del /Q ..\_ROUTES_READYGIT_\*.*
rmdir /Q /S ..\_ROUTES_READYGIT_\ICONS
rmdir /Q /S ..\_ROUTES_READYGIT_\INSTRESOURCES
rmdir /Q /S ..\_ROUTES_READYGIT_\SOLVER
rmdir /Q /S ..\_ROUTES_READYGIT_\READY\MAIN_DLLs
rmdir /Q /S ..\_ROUTES_READYGIT_\READY\MapCreator
rmdir /Q /S ..\_ROUTES_READYGIT_\READY\Service
rmdir /Q /S ..\_ROUTES_READYGIT_\READY\TEST
rmdir /Q /S ..\_ROUTES_READYGIT_\READY\TOOLS
copy *.* ..\_ROUTES_READYGIT_\
copy READY\*.* ..\_ROUTES_READYGIT_\READY
copy /Y READY\_SHAPES_\*.xml ..\_ROUTES_READYGIT_\READY\_SHAPES_
copy /Y READY\_SHAPES_\*.txt ..\_ROUTES_READYGIT_\READY\_SHAPES_
copy /Y READY\_SHAPES_\*.rar ..\_ROUTES_READYGIT_\READY\_SHAPES_
copy /Y READY\_SHAPES_\*.xlsx ..\_ROUTES_READYGIT_\READY\_SHAPES_
xcopy /S /E /I ICONS ..\_ROUTES_READYGIT_\ICONS
xcopy /S /E /I INSTRESOURCES ..\_ROUTES_READYGIT_\INSTRESOURCES
xcopy /S /E /I SOLVER ..\_ROUTES_READYGIT_\SOLVER
xcopy /S /E /I READY\MAIN_DLLs ..\_ROUTES_READYGIT_\READY\MAIN_DLLs
xcopy /S /E /I READY\MapCreator ..\_ROUTES_READYGIT_\READY\MapCreator
xcopy /S /E /I READY\Service ..\_ROUTES_READYGIT_\READY\Service
xcopy /S /E /I READY\TEST ..\_ROUTES_READYGIT_\READY\TEST
xcopy /S /E /I READY\TOOLS ..\_ROUTES_READYGIT_\READY\TOOLS
@echo ****** DONE ******
pause